# Generated by Django 3.2.2 on 2021-05-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('narrator', models.CharField(max_length=100)),
                ('duration_in_seconds', models.IntegerField()),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('podcast_name', models.CharField(max_length=100)),
                ('duration_in_seconds', models.IntegerField()),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
                ('host', models.CharField(max_length=100)),
                ('participant', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('song_name', models.CharField(max_length=100)),
                ('duration_in_seconds', models.IntegerField()),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
